Diagramas de Estado e Atividade
Caslus/bodyfit pull request #2
Opened 2023-05-23 23:02 UTC by Merlin262

2023-05-23 23:25 UTC, Caslus requested changes
### mudanças:
- renomear pastas para seguir padrão do repositório (letras sem capitalização)
- mudar o nome dos diagramas
![image](https://github.com/Caslus/bodyfit/assets/22855640/aefd5fd3-2c7c-412a-b224-3e067c8263bb)
- gerar diagramas (tools -> export image -> current diagram -> png)
![image](https://github.com/Caslus/bodyfit/assets/22855640/f50cf3ed-d5d9-46d3-8fc4-83d9b85793a1)

2023-05-25 22:53 UTC, Caslus approved these changes
me parece ok, vou pedir para o pedro dar uma olhada tbm...
na próxima tenta não fazer 1 commit por arquivo, bota tudo q tiver em um commit só, se precisar me chama que eu te ensino a fazer

2023-05-25 23:58 UTC, zPedroka requested changes
Acho que no diagrama de atividade de pagamento tinha que ter uma parte para o pagamento que n foi realizado, igual no diagrama geral...

2023-05-25 23:58 UTC, zPedroka requested changes
Acho que no diagrama de atividade de pagamento tinha que ter uma parte para o pagamento que n foi realizado, igual no diagrama geral...

2023-05-26 18:59 UTC, Caslus approved these changes

2023-05-26 19:36 UTC, zPedroka approved these changes

2023-05-26 19:59 UTC, merged